name: orange_todo

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0 

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.9
  flutter_slidable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.1.11

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    # Add more assets if needed

flutter_native_splash:
  color: "#F3DDC0"
  image: assets/png/LOGO_big.png
  
android_12:
  color: "#F3DDC0"
  image: assets/png/LOGO_big.png

  
